# Generated by Django 3.2.16 on 2023-01-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('requirements', models.TextField()),
                ('fall_deadline', models.DateTimeField()),
                ('winter_deadline', models.DateTimeField()),
                ('spring_deadline', models.DateTimeField()),
                ('summer_deadline', models.DateTimeField()),
                ('link', models.URLField()),
                ('degree_lvl', models.CharField(max_length=100)),
                ('course', models.BooleanField()),
                ('project', models.BooleanField()),
                ('thesis', models.BooleanField()),
                ('fee', models.IntegerField()),
                ('period', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('featured', models.BooleanField()),
                ('lvl', models.PositiveSmallIntegerField(choices=[(1, 'Bachelor'), (2, 'Master'), (3, 'Doctoral')])),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('website', models.URLField()),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('ranking', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('featured', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('overview', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('featured', models.BooleanField()),
                ('university', models.ManyToManyField(to='octapply.University')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('interest_field', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('faculty_page', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('google_scholar', models.URLField()),
                ('research_gate', models.URLField()),
                ('rate', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('featured', models.BooleanField()),
                ('university', models.ManyToManyField(to='octapply.University')),
            ],
        ),
    ]
