# Generated by Django 3.2.16 on 2023-01-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='google_scholar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='rate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='research_gate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='professor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='fall_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='spring_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='summer_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='winter_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
