# Generated by Django 3.2.16 on 2023-01-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapply', '0003_auto_20230127_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='professor',
            name='faculty_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='interest_field',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='major',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
