# Generated by Django 3.2.16 on 2023-02-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapply', '0007_alter_program_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='lang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
