# Generated by Django 3.2.16 on 2023-02-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapply', '0009_alter_professor_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='university',
            field=models.ManyToManyField(to='octapply.University'),
        ),
    ]
