# Generated by Django 3.2.16 on 2023-02-05 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octapply', '0010_alter_professor_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='university',
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uni', to='octapply.university'),
            preserve_default=False,
        ),
    ]
