# Generated by Django 3.2.16 on 2023-02-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octapply', '0011_auto_20230205_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='university',
        ),
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uniprof', to='octapply.university'),
            preserve_default=False,
        ),
    ]
