# Generated by Django 3.2.16 on 2023-02-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapply', '0012_auto_20230208_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
